version: '3.7'

volumes:
    apps-db:
    auth-db:
    templates-db:
    projects-db:
    user-code:

services:
    reverse-proxy:
        container_name: cake-core-nginx
        image: nginx
        ports:
            - 127.0.0.1:${LISTEN_PORT}:80
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro

    apps:
        image: images.cakerobotics.com/mostafa/apps:latest
        container_name: cake-apps
        depends_on:
            - apps-db
            - auth
        environment:
            POSTGRES_HOST: apps-db
            POSTGRES_USER: cake
            POSTGRES_PASSWORD: ${APPS_POSTGRES_PASSWORD}
            POSTGRES_DB: apps
            AUTH_SERVICE: http://auth:8000
            USER_CODE_PATH: /USER_CODE
        restart: always
        volumes:
            - user-code:/USER_CODE
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    apps-db:
        image: postgres
        container_name: cake-apps-db
        environment:
            POSTGRES_USER: cake
            POSTGRES_PASSWORD: ${APPS_POSTGRES_PASSWORD}
            POSTGRES_DB: apps
        restart: always
        volumes:
            - apps-db:/var/lib/postgresql/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    auth:
        image: images.cakerobotics.com/mostafa/auth:latest
        container_name: cake-auth
        depends_on:
            - auth-db
        environment:
            POSTGRES_HOST: auth-db
            POSTGRES_USER: cake
            POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
            POSTGRES_DB: auth
            JWT_SECRET: ${AUTH_JWT_SECRET}
            REQUIRE_REGISTERATION_TOKEN: ${REQUIRE_REGISTERATION_TOKEN}
            ADMIN_USERNAME: ${ADMIN_USERNAME}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
        restart: always
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    auth-db:
        image: postgres
        container_name: cake-auth-db
        environment:
            POSTGRES_USER: cake
            POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
            POSTGRES_DB: auth
        restart: always
        volumes:
            - auth-db:/var/lib/postgresql/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    templates:
        image: images.cakerobotics.com/mostafa/templates:latest
        container_name: cake-templates
        depends_on:
            - templates-db
            - auth
        environment:
            MONGO_HOST: templates-db
            MONGO_PORT: 27017
            MONGO_USER: cake
            MONGO_PASSWORD: ${TEMPLATES_MONGO_PASSWORD}
            AUTH_SERVICE: http://auth:8000
        restart: always
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    templates-db:
        image: mongo
        container_name: cake-templates-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: cake
            MONGO_INITDB_ROOT_PASSWORD: ${TEMPLATES_MONGO_PASSWORD}
        restart: always
        volumes:
            - templates-db:/data/db
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    projects:
        image: images.cakerobotics.com/mostafa/projects:latest
        container_name: cake-projects
        depends_on:
            - projects-db
            - auth
        environment:
            MONGO_HOST: projects-db
            MONGO_PORT: 27017
            MONGO_USER: cake
            MONGO_PASSWORD: ${PROJECTS_MONGO_PASSWORD}
            AUTH_SERVICE: http://auth:8000
            TEMPLATES_SERVICE: http://templates:8000
        restart: always
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro

    projects-db:
        image: mongo
        container_name: cake-projects-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: cake
            MONGO_INITDB_ROOT_PASSWORD: ${PROJECTS_MONGO_PASSWORD}
        restart: always
        volumes:
            - projects-db:/data/db
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
