pipeline {
  agent any
  stages {
    stage('Build Docs') {
      steps {
        script {
          sh '${WORKSPACE}/docs/make.sh'
        }
      }
    }

    stage('Publish Docs') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'jenkins-keycloak', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
            env.TOKEN = sh(script: '''
            curl -H "Content-Type: application/json" -d "{\\"username\\": \\"${USERNAME}\\", \\"password\\": \\"${PASSWORD}\\"}" https://utils.france-1.servers.cakerobotics.com/get-token
            ''', returnStdout: true)
            sh '''
            set +x
            echo "Using ${USERNAME}:*****"
            TEMPFILE=$(mktemp)
            curl -o ${TEMPFILE} -H "Content-Type: application/json" -H "Authorization: Bearer ${TOKEN}" -F "file=@${WORKSPACE}/docs/index.html" https://utils.france-1.servers.cakerobotics.com/publish-api-doc/auth
            cat ${TEMPFILE} | grep Success
            set -x
            '''
          }
        }
      }
    }

    stage('Build') {
      steps {
        script {
          dockerImage = docker.build "images.cakerobotics.com/mostafa/auth:latest", "."
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh '${WORKDIR}/run-tests.sh'
        }

      }
    }

    stage('Push') {
      steps {
        script {
          withDockerRegistry(credentialsId: 'jenkins-keycloak', url: 'https://images.cakerobotics.com/v2/') {
            dockerImage.push()
          }
        }

      }
    }

    stage('Deploy') {
      steps {
        script {
          withCredentials([usernamePassword(credentialsId: 'jenkins-keycloak', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
            env.TOKEN = sh(script: '''
            curl -H "Content-Type: application/json" -d "{\\"username\\": \\"${USERNAME}\\", \\"password\\": \\"${PASSWORD}\\"}" https://utils.france-1.servers.cakerobotics.com/get-token
            ''', returnStdout: true)
            sh '''
            set +x
            echo "Using ${USERNAME}:*****"
            TEMPFILE=$(mktemp)
            curl -o ${TEMPFILE} -H "Content-Type: application/json" -H "Authorization: Bearer ${TOKEN}" -d \'{"service": "auth", "directory": "/services/cake"}\' https://utils.france-1.servers.cakerobotics.com/docker-compose-deliver
            cat ${TEMPFILE} | grep Success
            set -x
            '''
          }
        }
      }
    }
  }
}
