version: '3.7'

networks:
    default:
        external:
            name: sim-test

services:
    sim:
        build:
            context: ../
        entrypoint: /bin/sh -c "cd /app && yarn test"
        environment:
            AUTH_SERVICE: http://auth:8000
            MONGO_HOST: sim-db
            MONGO_PORT: 27017
            MONGO_USER: cake
            MONGO_PASSWORD: cake
            PROJECTS_SERVICE: http://projects:8000
            TEST_ADMIN_PASSWORD: admin
            TEST_ADMIN_USERNAME: admin
        tty: true
