version: '3.7'

networks:
    apps-test:

services:
    apps-db:
        image: postgres
        environment:
            POSTGRES_DB: apps
            POSTGRES_USER: cake
            POSTGRES_PASSWORD: cake
        networks:
            - apps-test
        ports:
            - 127.0.0.1:5432:5432

    auth:
        image: images.cakerobotics.com/mostafa/auth:latest
        environment:
            POSTGRES_HOST: auth-db
            POSTGRES_USER: cake
            POSTGRES_PASSWORD: cake
            POSTGRES_DB: auth
            JWT_SECRET: cake
            REQUIRE_REGISTERATION_TOKEN: 0
            ADMIN_USERNAME: admin
            ADMIN_PASSWORD: admin
            ADMIN_EMAIL: admin@example.com
        depends_on:
            - auth-db
        networks:
            - apps-test
        ports:
            - 127.0.0.1:5005:8000

    auth-db:
        image: postgres
        environment:
            POSTGRES_USER: cake
            POSTGRES_PASSWORD: cake
            POSTGRES_DB: auth
        networks:
            - apps-test
