version: '3.7'

networks:
    default:
        external:
            name: apps-test

services:
    apps:
        build:
            context: ../
        entrypoint: /bin/sh -c "cd /app && yarn test"
        environment:
            AUTH_SERVICE: http://auth:8000
            POSTGRES_DB: apps
            POSTGRES_HOST: apps-db
            POSTGRES_PASSWORD: cake
            POSTGRES_USER: cake
            TEST_ADMIN_PASSWORD: admin
            TEST_ADMIN_USERNAME: admin
            USER_CODE_PATH: /USER_CODE
        tty: true
