version: '3.7'

services:
    reverse-proxy:
        image: nginx
        container_name: cake-ui-nginx
        ports:
            - 127.0.0.1:${LISTEN_PORT}:80
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro

    main-website:
        image: images.cakerobotics.com/mostafa/main-website:latest
        container_name: cake-main-website-server
        restart: always

    auth-ui:
        image: images.cakerobotics.com/mostafa/auth-ui:latest
        container_name: cake-auth-ui
        restart: always
